language: php

php:
  - 5.4
  - 5.5
  - 5.6
install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:1.0.0-beta4"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.clover --exclude-group mssql,oci,wincache,xcache,zenddata
 - |
    if (php --version | grep -i HipHop > /dev/null); then
      echo "Skipping basic application tests on HHVM"
    else
      cd web
      php -S localhost:8080 > /dev/null 2>&1 &
      cd ../tests
      codecept run
    fi
  - |
    if (php --version | grep -i HipHop > /dev/null); then
      echo "Skipping advanced application tests on HHVM"
    else
      cd apps/advanced
      php -S localhost:8080 > /dev/null 2>&1 &
      cd tests
      codecept run
    fi
